load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//subtitler/video:__subpackages__"])

cc_library(
    name = "video_utils",
    srcs = ["video_utils.cpp"],
    hdrs = ["video_utils.h"],
    deps = [],
)
