load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//subtitler/experimental:__subpackages__"])

# autogen_timeline.cpp is obtained from running rcc on the timeline.qrc file.
cc_library(
    name = "resources",
    srcs = ["autogen_timeline.cpp"],
    deps = [],
)
