load("@com_justbuchanan_rules_qt//:qt.bzl", "qt_cc_library")

package(default_visibility = ["//subtitler/gui:__subpackages__"])

qt_cc_library(
    name = "play_button",
    srcs = ["play_button.cpp"],
    hdrs = ["play_button.h"],
    deps = ["@qt//:qt_widgets"],
)

qt_cc_library(
    name = "step_button",
    srcs = ["step_button.cpp"],
    hdrs = ["step_button.h"],
    deps = ["@qt//:qt_widgets"],
)
